INSERT INTO ZZZ_USERS (ID, VERSION, AD) VALUES (-1, 0, 'John Doe');
INSERT INTO ZZZ_USERS (ID, VERSION, AD) VALUES (-2, 0, 'Richard Roe');

INSERT INTO ZZZ_SPOTS (ID, VERSION, Code) VALUES (-1, 0, 'Spot One');
INSERT INTO ZZZ_SPOTS (ID, VERSION, Code) VALUES (-2, 0, 'Spot Two');
