INSERT INTO ZZZ_USERS (ID, VERSION, AD) VALUES (-1, 0, 'John Doe');
INSERT INTO ZZZ_USERS (ID, VERSION, AD) VALUES (-2, 0, 'Richard Roe');

INSERT INTO ZZZ_SPOTS (ID, VERSION, Code) VALUES (-1, 0, 'Spot One');
INSERT INTO ZZZ_SPOTS (ID, VERSION, Code) VALUES (-2, 0, 'Spot Two');


INSERT INTO ZZZ_RESERVATIONS (ID, VERSION, USER_ID, SPOT_ID, START_, END_, STATUS ) VALUES (-1, 0, -1, -2, '2021-09-01 15:12:00', '2021-09-01 17:12:00', NULL);